repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format-python-files
        name: Format python files
        entry: black
        files: ^.*.py$
        language: python_venv
      - id: sort-imports
        name: Sort imports
        entry: isort --profile black
        files: ^.*.py$
        language: python_venv
      - id: run-mypy
        name: Run mypy
        entry: mypy --ignore-missing-imports
        files: ^.*.py$
        language: python_venv
